### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by frohoff** [DirectDefense/SuperSerial#1]

**Comment by hvqzao** [comment]
*bump*, and also the license

**Comment by DirectDefense** [comment]
Added source and license info, thanks guys!

**Comment by hvqzao** [comment]
Thank you for that!
Please consider adding third check - for base64 encoded serialized data, which seems to be missing. Check should search actual request/responses for starting sequence: "rO0AB".

**Comment by DirectDefense** [comment]
The "rO0AB" check has been added for server responses only. Support was not added for requests because Burp detects this natively using the "Serialized object in HTTP message" scan issue.
